"""Base de datos de personajes para DBZ Budokai HD Collection.

Copyright (c) NovaPowers. Released under the MIT License.
Firmado por NovaPowers.

Maestro de nombres/variantes/jugabilidad por CODIGO de personaje (el prefijo
del label, ej. 'GOK', 'X20G', 'XUUB'). El prefijo se normaliza quitando la
'X' inicial. Las claves SIEMPRE sin 'X'.

Fuentes (16/08-17/08):
  - data_us.afs del B1 (escaneo b1_chars_scan.txt): 446 bins con labels.
  - data_sp.afs del B1 (scan_catalog): slots de combate por personaje.
  - data_cmn.afs del B3 (scan de #AMB real, 17/08): bins reales por codigo.
  - DBZ_B3_GH_Character_Bin_List.txt (VERIFICADO: coincide con el AFS real).
  - Budokai 1 Models Converted to AMB (códigos de archivos PS2).
  - All_Character_Slots Infinite World.txt.

Cada entrada: (nombre, variante, jugable, nota)
  jugable: True/False/None(desconocido)
  variante: traje/transformación distinta para el mismo personaje.
  nota: aclaración (no jugable, historia, etc.)
"""

# ---------------------------------------------------------------------------
# B3 HD (Budokai 3): bin REAL del data_cmn.afs -> (nombre, variante, jugable, nota)
# Los numeros de bin son los del AFS real (escaneo 17/08), y COINCIDEN con la
# lista DBZ_B3_GH_Character_Bin_List.txt (Budokai GH/Collector). Solo se listan
# los bins de MODELO; los bins de animacion/aura/efecto que aparecen al final
# de cada bloque NO se incluyen (se descartan por no estar en la lista GH).
# ---------------------------------------------------------------------------
B3 = {
    # bin : (nombre, variante, jugable, nota)
    70:  ("Android 16", "", True, ""),
    71:  ("Android 16", "Traje alternativo", True, ""),
    75:  ("Android 17", "", True, ""),
    76:  ("Android 17", "Traje alternativo", True, ""),
    80:  ("Android 18", "", True, ""),
    81:  ("Android 18", "Traje alternativo", True, ""),
    82:  ("Android 18", "Traje 3", True, ""),
    86:  ("Syn Shenron", "", True, "Li Shenron"),
    87:  ("Syn Shenron", "Negro", True, "Omega Shenron"),
    91:  ("Dr. Gero", "", None, "No jugable (historia)"),
    92:  ("Dr. Gero", "Traje alternativo", None, "No jugable (historia)"),
    96:  ("Babidi", "", None, "No jugable"),
    99:  ("Bardock", "", True, ""),
    100: ("Bardock", "Traje alternativo", True, ""),
    104: ("Buu Gohan", "", True, "Buuhan"),
    105: ("Buu Gohan", "Traje alternativo", True, "Buuhan"),
    107: ("Buu Gotenks", "", True, "Buutenks"),
    108: ("Buu Gotenks", "Traje alternativo", True, "Buutenks"),
    110: ("Bulma", "", None, "No jugable"),
    114: ("Buu Ghost", "Kamikaze", None, "Fantasma de Buu"),
    116: ("Buu Piccolo", "", True, "Buucolo"),
    117: ("Buu Piccolo", "Traje alternativo", True, "Buucolo"),
    119: ("Broly", "", True, ""),
    120: ("Broly", "LSSJ", True, ""),
    121: ("Broly", "Traje alternativo", True, ""),
    122: ("Broly", "LSSJ alt", True, ""),
    128: ("Majin Buu", "Gordo", True, "Fat Buu"),
    129: ("Majin Buu", "Gordo (2)", True, "Fat Buu"),
    133: ("Super Buu", "", True, ""),
    134: ("Super Buu", "Traje alternativo", True, ""),
    141: ("Kid Buu", "", True, ""),
    142: ("Kid Buu", "Traje alternativo", True, ""),
    146: ("Cell", "Forma 1", True, "Imperfecto"),
    147: ("Cell", "Forma 2", True, "Semi-perfecto"),
    148: ("Cell", "Forma 3", True, "Perfecto"),
    149: ("Cell", "Forma 1 alt", True, ""),
    150: ("Cell", "Forma 2 alt", True, ""),
    151: ("Cell", "Forma 3 alt", True, ""),
    160: ("Cell Jr.", "", True, ""),
    161: ("Cell Jr.", "Traje alternativo", True, ""),
    166: ("Cooler", "Forma base", True, ""),
    167: ("Cooler", "Forma final", True, ""),
    168: ("Metal Cooler", "", True, ""),
    169: ("Cooler", "Forma base alt", True, ""),
    170: ("Cooler", "Forma final alt", True, ""),
    171: ("Metal Cooler", "Traje alternativo", True, ""),
    176: ("Dabura", "", True, ""),
    177: ("Dabura", "Traje alternativo", True, ""),
    181: ("Freeza", "Forma 1", True, ""),
    182: ("Freeza", "Forma 2", True, ""),
    183: ("Freeza", "Forma 3", True, ""),
    184: ("Freeza", "Forma 4", True, "Final"),
    185: ("Freeza", "100%", True, "Forma final 100%"),
    186: ("Freeza", "Cibernetico", True, "Freezabot / Mecha"),
    187: ("Freeza", "Forma 1 alt", True, ""),
    188: ("Freeza", "Forma 2 alt", True, ""),
    189: ("Freeza", "Forma 3 alt", True, ""),
    190: ("Freeza", "Forma 4 alt", True, ""),
    191: ("Freeza", "100% alt", True, ""),
    192: ("Freeza", "Cibernetico alt", True, ""),
    193: ("Freeza", "Forma 1 con nave", True, "Mini nave espacial"),
    214: ("Veku", "Gogeta gordo", True, "Fusion fallida"),
    215: ("Veku", "Gogeta gordo alt", True, ""),
    217: ("Gogeta", "SSJ", True, ""),
    218: ("Gogeta", "SSJ4", True, ""),
    219: ("Gogeta", "SSJ alt", True, ""),
    220: ("Gogeta", "SSJ4 alt", True, ""),
    225: ("Gohan", "Adulto (violeta)", True, ""),
    226: ("Gohan", "Adulto SSJ (violeta)", True, ""),
    227: ("Gohan", "Adulto Mistico", True, ""),
    228: ("Gohan", "Adulto (naranja)", True, ""),
    229: ("Gohan", "Adulto SSJ (naranja)", True, ""),
    230: ("Gohan", "Adulto Mistico (naranja)", True, ""),
    235: ("Gohan", "Saga Cell", True, "Adolescente"),
    236: ("Gohan", "Saga Cell SSJ", True, ""),
    238: ("Gohan", "Saga Cell armadura", True, ""),
    239: ("Gohan", "Saga Cell armadura SSJ", True, ""),
    240: ("Gohan", "Saga Cell armadura SSJ2", True, ""),
    246: ("Gohan", "Nino", True, ""),
    247: ("Gohan", "Namek armadura", True, ""),
    248: ("Gohan", "Namek", True, ""),
    252: ("Goku", "Nino", True, ""),
    253: ("Goku", "Nino alt", True, ""),
    258: ("Ginyu", "", True, ""),
    259: ("Ginyu", "Traje alternativo", True, ""),
    264: ("Goku", "Normal", True, ""),
    265: ("Goku", "Kaiohken", True, ""),
    266: ("Goku", "SSJ", True, ""),
    267: ("Goku", "SSJ2", True, ""),
    268: ("Goku", "SSJ3", True, ""),
    269: ("Goku", "SSJ4", True, ""),
    270: ("Goku", "Normal alt", True, ""),
    271: ("Goku", "Kaiohken alt", True, ""),
    272: ("Goku", "SSJ alt", True, ""),
    273: ("Goku", "SSJ2 alt", True, ""),
    274: ("Goku", "SSJ3 alt", True, ""),
    275: ("Goku", "SSJ4 alt", True, ""),
    276: ("Goku", "Traje roto", True, "Battle damage"),
    277: ("Goku", "Traje roto + Kaiohken", True, ""),
    278: ("Goku", "Traje roto SSJ", True, ""),
    279: ("Goku", "Traje roto SSJ2", True, ""),
    280: ("Goku", "Traje roto SSJ3", True, ""),
    281: ("Goku", "Angelic", True, "Goku + Ginyu?"),
    282: ("Goku", "Angelic Kaiohken", True, ""),
    283: ("Goku", "Angelic SSJ", True, ""),
    284: ("Goku", "Angelic SSJ2", True, ""),
    285: ("Goku", "Angelic SSJ3", True, ""),
    286: ("Goku", "Angelic SSJ4", True, ""),
    287: ("Goku", "Angelic SSJ4 (2)", True, ""),
    293: ("Great Saiyaman", "", True, ""),
    294: ("Great Saiyaman", "Traje alternativo", True, ""),
    298: ("Goten", "", True, ""),
    299: ("Goten", "SSJ", True, ""),
    300: ("Goten", "Traje alternativo", True, ""),
    301: ("Goten", "SSJ alt", True, ""),
    305: ("Gotenks", "Normal", True, ""),
    306: ("Gotenks", "SSJ", True, ""),
    307: ("Gotenks", "SSJ3", True, ""),
    308: ("Gotenks", "Normal alt", True, ""),
    309: ("Gotenks", "SSJ alt", True, ""),
    310: ("Gotenks", "SSJ3 alt", True, ""),
    312: ("Ghost Gotenks", "", True, "Gotenks fantasma"),
    313: ("Ghost Gotenks", "SSJ3", True, ""),
    314: ("Fat Gotenks", "", True, ""),
    315: ("Fat Gotenks", "Traje alternativo", True, ""),
    325: ("Kibito", "", None, "No jugable"),
    327: ("Krillin", "Sin pelo / con pelo / armadura", True, "Varios"),
    328: ("Krillin", "Con pelo", True, ""),
    329: ("Krillin", "Armadura", True, ""),
    334: ("Kibito Kai", "", True, "Kaioh-Kibito"),
    335: ("Kibito Kai", "Traje alternativo", True, ""),
    339: ("Kaio-Shin", "", True, ""),
    340: ("Kaio-Shin", "Traje alternativo", True, ""),
    345: ("Nappa", "", True, ""),
    346: ("Nappa", "Traje alternativo", True, ""),
    350: ("Piccolo", "Normal", True, ""),
    351: ("Piccolo", "Nail fusion", True, ""),
    352: ("Piccolo", "Capa larga", True, ""),
    353: ("Piccolo Daimao", "", True, "Demon King Piccolo"),
    358: ("Recoome", "", True, ""),
    359: ("Recoome", "Traje alternativo", True, ""),
    360: ("Raditz", "", True, ""),
    361: ("Raditz", "Traje alternativo", True, ""),
    363: ("Saibaman", "", True, ""),
    364: ("Saibaman", "Traje alternativo", True, ""),
    376: ("Mr. Satan", "Con pelo", True, "Hercule"),
    377: ("Mr. Satan", "", True, "Hercule"),
    378: ("Mr. Satan", "Traje alternativo", True, ""),
    383: ("Trunks", "Nino", True, ""),
    384: ("Trunks", "Nino SSJ", True, ""),
    385: ("Trunks", "Nino alt", True, ""),
    386: ("Trunks", "Nino SSJ alt", True, ""),
    390: ("Trunks", "Futuro espada", True, ""),
    391: ("Trunks", "Futuro espada SSJ", True, ""),
    392: ("Trunks", "Futuro espada alt", True, ""),
    393: ("Trunks", "Futuro espada SSJ alt", True, ""),
    394: ("Trunks", "Futuro armadura", True, ""),
    395: ("Trunks", "Futuro armadura SSJ", True, ""),
    400: ("Tenshinhan", "", True, ""),
    401: ("Tenshinhan", "Traje alternativo", True, ""),
    405: ("Uub", "", True, ""),
    406: ("Uub", "Traje alternativo", True, ""),
    410: ("Videl", "", True, ""),
    411: ("Videl", "Traje alternativo", True, ""),
    416: ("Vegeta", "Sin armadura", True, ""),
    417: ("Vegeta", "Sin armadura SSJ", True, ""),
    418: ("Vegeta", "SSJ4", True, ""),
    419: ("Majin Vegeta", "", True, ""),
    420: ("Vegeta", "Armadura androides", True, ""),
    421: ("Vegeta", "Armadura androides SSJ", True, ""),
    422: ("Vegeta", "SSJ4 alt", True, ""),
    423: ("Majin Vegeta", "Armadura androides", True, ""),
    424: ("Vegeta", "Armadura saga Saiyan", True, ""),
    425: ("Vegeta", "Armadura saga Saiyan SSJ", True, ""),
    426: ("Majin Vegeta", "Armadura saga Saiyan", True, ""),
    427: ("Vegeta", "Armadura Namek", True, ""),
    428: ("Vegeta", "Armadura Namek SSJ", True, ""),
    429: ("Majin Vegeta", "Armadura Namek", True, ""),
    438: ("Vegito", "", True, ""),
    439: ("Vegito", "SSJ", True, ""),
    440: ("Vegito", "Traje alternativo", True, ""),
    441: ("Vegito", "SSJ alt", True, ""),
    445: ("Yamcha", "Pelo corto", True, ""),
    446: ("Yamcha", "Vestimenta amarilla", True, ""),
    447: ("Yamcha", "Pelo largo", True, ""),
}

# ---------------------------------------------------------------------------
# B1 HD (Budokai 1). codigo -> (nombre, variante, jugable, nota)
# Jugables: los que tienen slots de combate en data_sp.afs.
# No jugables: historia/cinematica (pero swapeables, tienen modelo 3D).
# ---------------------------------------------------------------------------
B1 = {
    "GOK": ("Goku", "", True, "Muchas transformaciones"),
    "VGT": ("Vegeta", "", True, ""),
    "GHN": ("Gohan", "", True, ""),
    "KLL": ("Krillin", "", True, ""),
    "PIC": ("Piccolo", "", True, ""),
    "TSH": ("Tenshinhan", "", True, ""),
    "TJR": ("Tenshinhan", "Joven", True, ""),
    "TRX": ("Trunks", "", True, "Futuro"),
    "YMC": ("Yamcha", "", True, ""),
    "CHZ": ("Chaozu", "", True, ""),
    "FRZ": ("Freeza", "", True, "Varias formas"),
    "CLD": ("Cell", "", True, "Varias formas"),
    "RAD": ("Raditz", "", True, ""),
    "RCM": ("Recoome", "", True, ""),
    "SBM": ("Saibaman", "", True, ""),
    "NAP": ("Nappa", "", True, ""),
    "GNY": ("Ginyu", "", True, ""),
    "ZBN": ("Zarbon", "", True, ""),
    "16G": ("Android 16", "", True, ""),
    "17G": ("Android 17", "", True, ""),
    "18G": ("Android 18", "", True, ""),
    "19G": ("Android 19", "", True, ""),
    "20G": ("Dr. Gero", "Cuerpo", False, "No jugable (historia)"),
    "20G_FACE": ("Dr. Gero", "Solo cara", False, "No jugable (historia)"),
    "GSM": ("Great Saiyaman", "", True, ""),
    "STN": ("Mr. Satan", "", True, "Hercule"),
    "THL": ("Gohan", "Alternativo", None, "Gohan?/Thales? (saga Cell)"),
    "JES": ("Jeice", "", False, "Fuerzas Ginyu"),
    "GRD": ("Guldo", "", False, "Fuerzas Ginyu"),
    "BAT": ("Burter", "", False, "Fuerzas Ginyu"),
    "GRY": ("? (Fuerzas Ginyu)", "", False, "Desconocido"),
    "BBR": ("? (Fuerzas Ginyu)", "", False, "Desconocido"),
    "DDR": ("Dodoria", "", False, "Fuerzas de Freeza"),
    "DND": ("Dende", "", False, "No jugable"),
    "NER": ("Nail", "", False, "Namekiano"),
    "KWI": ("Cui", "", False, "Fuerzas de Vegeta"),
    "BLM": ("Bulma", "", False, "No jugable"),
    "YJR": ("Yajirobe", "", False, "No jugable"),
    "WOO": ("Oolong", "", False, "No jugable"),
    "MPP": ("Mr. Popo", "", False, "No jugable"),
    "KAM": ("Maestro Roshi", "", False, "Kame-Sennin"),
    "POO": ("Popo", "", False, "No jugable"),
    "KIO": ("Kaio", "", False, "Rey Kai"),
    "GOD": ("Kami", "", False, "Dios Guardian"),
    "KRN": ("Korin", "", False, "Gato sagrado"),
    "KSN": ("? (Shenron)", "", None, "Desconocido"),
    "ZKA": ("Zenkai", "A", None, "Desconocido"),
    "ZKB": ("Zenkai", "B", None, "Desconocido"),
    "ZKC": ("Zenkai", "C", None, "Desconocido"),
    "ZKD": ("Zenkai", "D", None, "Desconocido"),
    "ZKE": ("Zenkai", "E", None, "Desconocido"),
    "ZKF": ("Zenkai", "F", None, "Desconocido"),
    "FDR": ("? (Freeza)", "", False, "Desconocido"),
    "FRG": ("? (Freeza)", "", False, "Desconocido"),
    "KIN": ("? (Shenron)", "", None, "Desconocido"),
    "HEM": ("? (historia)", "", False, "Desconocido"),
    "STC": ("Mr. Satan", "Con capa", False, "Hercule"),
    "DIN": ("? (historia)", "", False, "Desconocido"),
    "SEI": ("? (espectador)", "", False, "Desconocido"),
}

# ---------------------------------------------------------------------------
# B1 PS2 (Budokai 1 PS2 - modelos convertidos a AMB).
# codigo de archivo -> (nombre, variante, jugable, nota).
# Fuente: "Budokai 1 Models Converted to AMB" (labels escaneados de los #AMO0).
# ---------------------------------------------------------------------------
PS2 = {
    "16G": ("Android 16", "", True, ""),
    "17G": ("Android 17", "", True, ""),
    "18G": ("Android 18", "", True, ""),
    "19G": ("Android 19", "", True, ""),
    "20G": ("Dr. Gero", "", False, "No jugable (historia)"),
    "ANS": ("Android generico", "", False, "NS00_BODY"),
    "BAT": ("Burter", "", False, "Fuerzas Ginyu"),
    "BBR": ("? (Fuerzas Ginyu)", "", False, "Desconocido"),
    "BLM": ("Bulma", "", False, "No jugable"),
    "CCI": ("Cui", "", False, "Fuerzas de Vegeta"),
    "CEL": ("Cell", "", True, "Varias formas"),
    "CHZ": ("Chaozu", "", True, ""),
    "CLD": ("Cell", "", True, "Varias formas"),
    "CLJ": ("Cell Jr.", "", False, ""),
    "DDR": ("Dodoria", "", False, "Fuerzas de Freeza"),
    "DND": ("Dende", "", False, "No jugable"),
    "FDR": ("? (Freeza)", "", False, "Desconocido"),
    "FRG": ("Freeza", "Alternativo", False, "Desconocido"),
    "FRZ": ("Freeza", "", True, "Varias formas"),
    "GHN": ("Gohan", "", True, ""),
    "GNY": ("Ginyu", "", True, ""),
    "GOD": ("Kami", "", False, "Dios Guardian"),
    "GOK": ("Goku", "", True, "Muchas transformaciones"),
    "GRD": ("Guldo", "", False, "Fuerzas Ginyu"),
    "GRY": ("? (Fuerzas Ginyu)", "", False, "Desconocido"),
    "GSM": ("Great Saiyaman", "", True, ""),
    "JES": ("Jeice", "", False, "Fuerzas Ginyu"),
    "KAM": ("Maestro Roshi", "", False, "Kame-Sennin"),
    "KIO": ("Kaio", "", False, "Rey Kai"),
    "KLL": ("Krillin", "", True, ""),
    "KRN": ("Korin", "", False, "Gato sagrado"),
    "KSN": ("? (Shenron)", "", None, "Desconocido"),
    "KWI": ("Cui", "", False, "Fuerzas de Vegeta"),
    "MPP": ("Mr. Popo", "", False, "No jugable"),
    "NAP": ("Nappa", "", True, ""),
    "NER": ("Nail", "", False, "Namekiano"),
    "PIC": ("Piccolo", "", True, ""),
    "POO": ("Popo", "", False, "No jugable"),
    "RAD": ("Raditz", "", True, ""),
    "RCM": ("Recoome", "", True, ""),
    "SBM": ("Saibaman", "", True, ""),
    "STN": ("Mr. Satan", "", True, "Hercule"),
    "TRX": ("Trunks", "", True, "Futuro"),
    "TSH": ("Tenshinhan", "", True, ""),
    "VGT": ("Vegeta", "", True, ""),
    "WOO": ("Oolong", "", False, "No jugable"),
    "YJR": ("Yajirobe", "", False, "No jugable"),
    "YMC": ("Yamcha", "", True, ""),
    "ZAK": ("Zenkai", "", None, "ZKA-ZKF"),
    "ZBN": ("Zarbon", "", True, ""),
}