// dbz1 - ReXGlue Recompiled Project
// Generated by: rexglue init
// Adapted from original WistfulHopes/DBZ1 main.cpp to new ReXGlue API

#include "generated/dbz1_init.h"

#include <rex/cvar.h>
#include <rex/filesystem.h>
#include <rex/filesystem/afs.h>
#include <rex/runtime.h>
#include <rex/logging.h>
#include <rex/system/function.h>
#include <rex/system/xthread.h>
#include <rex/system/kernel_state.h>
#include <rex/graphics/graphics_system.h>
#include <rex/ui/window.h>
#include <rex/ui/window_listener.h>
#include <rex/ui/windowed_app.h>
#include <rex/ui/graphics_provider.h>
#include <rex/ui/immediate_drawer.h>
#include <rex/ui/imgui_drawer.h>
#include <rex/ui/imgui_dialog.h>
#include <rex/ui/keybinds.h>
#include <rex/rex_app.h>
#include <rex/audio/sdl/sdl_audio_system.h>
#include <rex/input/input_system.h>
#include <rex/kernel/init.h>
#include <rex/assert.h>

#include "launcher/settings.h"
#include "launcher/launcher_state.h"
#include "ingame/menu.h"
#include "region.h"

// Defined in src/launcher/settings.cpp (same executable).
REXCVAR_DECLARE(bool, dbz1_skip_launcher);

#include <imgui.h>

#include <spdlog/spdlog.h>

#include <atomic>
#include <algorithm>
#include <filesystem>
#include <thread>
#include <vector>

#if REX_PLATFORM_WIN32
#include <windows.h>
#include <dbghelp.h>
#pragma comment(lib, "dbghelp.lib")
#endif

class DebugOverlayDialog : public rex::ui::ImGuiDialog {
public:
    DebugOverlayDialog(rex::ui::ImGuiDrawer* imgui_drawer)
        : ImGuiDialog(imgui_drawer) {}
protected:
    void OnDraw(ImGuiIO& io) override {
        // Only visible when the user enables the FPS counter (Dev tab).
        if (!dbz1::settings::ShowFps()) {
            return;
        }
        ImGui::SetNextWindowPos(ImVec2(10, 10), ImGuiCond_FirstUseEver);
        ImGui::SetNextWindowSize(ImVec2(220, 60), ImGuiCond_FirstUseEver);
        ImGui::SetNextWindowBgAlpha(0.5f);
        if (ImGui::Begin("Debug##overlay", nullptr, ImGuiWindowFlags_NoCollapse)) {
            ImGui::Text("%.1f FPS (%.2f ms)", io.Framerate, 1000.0f / io.Framerate);
        }
        ImGui::End();
    }
};

class Dbz1App : public rex::ReXApp {
public:
    static std::unique_ptr<rex::ui::WindowedApp> Create(rex::ui::WindowedAppContext& ctx) {
        return std::make_unique<Dbz1App>(ctx);
    }

    Dbz1App(rex::ui::WindowedAppContext& ctx)
        : ReXApp(ctx, "dbz1", PPCImageConfig, "[game_directory]") {
        OutputDebugStringA("Dbz1App constructor START\n");
        AddPositionalOption("game_directory");
        OutputDebugStringA("Dbz1App constructor END\n");
    }

    // Called before Runtime::Setup() - configure GPU plugin
    void OnPreSetup(rex::RuntimeConfig& config) override {
        OutputDebugStringA("OnPreSetup START\n");
        config.gpu_plugin = "xenos";
        config.audio_factory = REX_AUDIO_BACKEND(rex::audio::sdl::SDLAudioSystem);
        config.input_factory = REX_INPUT_BACKEND(rex::input::CreateDefaultInputSystem);
        config.kernel_init = rex::kernel::InitializeKernel;
        OutputDebugStringA("OnPreSetup END\n");

        // User settings: load dbz1_user.toml (must run after the SDK config
        // so user values win) and forward the friendly cvars onto the SDK's
        // startup cvars before the window/presentation is created.
        dbz1::settings::LoadUserSettings();
        dbz1::settings::ApplyUserSettingsToSdk();
    }

    // Called after runtime is fully initialized, before window creation
    void OnPostSetup() override {
        OutputDebugStringA("OnPostSetup START\n");
        REXLOG_INFO("OnPostSetup - Runtime initialized, graphics system should be ready");
        SetupCrashHandler();
        CleanupOldArtifacts();
        OutputDebugStringA("OnPostSetup END\n");
        
        // Check graphics system state
        if (auto* rt = runtime()) {
            if (auto* gs = rt->graphics_system()) {
                OutputDebugStringA("Graphics system: YES\n");
                if (auto* presenter = gs->presenter()) {
                    OutputDebugStringA("Presenter: YES\n");
                } else {
                    OutputDebugStringA("Presenter: NO\n");
                }
            } else {
                OutputDebugStringA("Graphics system: NO\n");
            }
        }
    }

    // Called after ImGui drawer is created - add custom dialogs
    void OnCreateDialogs(rex::ui::ImGuiDrawer* drawer) override {
        OutputDebugStringA("OnCreateDialogs START\n");
        if (!debug_overlay_) {
            debug_overlay_ = std::make_unique<DebugOverlayDialog>(drawer);
        }
        imgui_drawer_ = drawer;  // Store for later use in OnPostLaunchModule

        // Pre-game launcher. Its "Play" button dismisses the dialog and
        // triggers the gated module launch (see LaunchModule override below).
        // NOTE: the dialog self-deletes on Close(), so we hold a raw pointer
        // (not unique_ptr) and null it from the on_play callback.
        if (!launcher_dialog_) {
            launcher_dialog_ = new dbz1::launcher::LauncherDialog(
                drawer, [this]() {
                    // The dialog self-deletes right after this callback returns
                    // (ImGuiDialog::Draw -> delete this). Join any in-flight
                    // model-pipeline worker FIRST: destroying the dialog (and
                    // its ModPipeline member) while the worker thread is still
                    // joinable would call std::terminate.
                    if (launcher_dialog_) {
                        launcher_dialog_->ShutdownPipeline();
                    }
                    launcher_dialog_ = nullptr;
                    try {
                        // The mod pipeline (run as a separate python process) may
                        // have written new mods / toggled enable states since the
                        // runtime last scanned the mods folder. Force a rescan so
                        // the game boots with the on-disk mod state instead of the
                        // stale one captured when the launcher started (otherwise a
                        // mod installed then "Play" pressed would be ignored).
                        rex::filesystem::AfsResetModCache();
                        ReXApp::LaunchModule();
                    } catch (const std::exception& e) {
                        REXLOG_ERROR("dbz1: exception in Play handler: {}", e.what());
                    } catch (...) {
                        REXLOG_ERROR("dbz1: unknown exception in Play handler");
                    }
                });
        }

        // F10 toggles the in-game dev overlay (only meaningful once running).
        rex::ui::RegisterBind("bind_dbz1_ingame", "F10", "Toggle in-game dev overlay", [this]() {
            if (!launched_.load(std::memory_order_acquire)) {
                return;  // Launcher not dismissed yet.
            }
            if (ingame_menu_) {
                ingame_menu_.reset();
            } else {
                ingame_menu_ = std::make_unique<dbz1::ingame::InGameMenu>(imgui_drawer_);
            }
        });

        OutputDebugStringA("OnCreateDialogs END\n");
    }

    // Called immediately before the main guest thread is created
    void OnPreLaunchModule() override {
        OutputDebugStringA("OnPreLaunchModule START\n");
        REXLOG_INFO("OnPreLaunchModule - about to launch guest thread");

        // The launcher may have changed the region after the runtime's initial
        // VFS setup. Re-apply the region device mount so game:\us points at the
        // currently selected region's assets.
        dbz1::ApplyRegionMount();

        OutputDebugStringA("OnPreLaunchModule END\n");
    }

    // Called after the main guest thread is created but before it starts executing
    void OnPostLaunchModule(rex::system::XThread* thread) override {
        (void)thread;
        OutputDebugStringA("OnPostLaunchModule START\n");
        REXLOG_INFO("OnPostLaunchModule - guest thread created and resumed");

        // The launcher was dismissed; arm the in-game overlay.
        launched_.store(true, std::memory_order_release);

        // Set up display window and ImGui drawer for the guest thread (like original main.cpp)
        if (auto* rt = runtime()) {
            OutputDebugStringA("OnPostLaunchModule - runtime available\n");
            if (window()) {
                rt->set_display_window(window());
                OutputDebugStringA("Set display window on runtime\n");
            } else {
                OutputDebugStringA("Window is null!\n");
            }
            if (imgui_drawer_) {
                rt->set_imgui_drawer(imgui_drawer_);
                OutputDebugStringA("Set ImGui drawer on runtime\n");
            } else {
                OutputDebugStringA("ImGui drawer is null!\n");
            }
        } else {
            OutputDebugStringA("Runtime is null!\n");
        }
        
        OutputDebugStringA("OnPostLaunchModule END\n");
    }

    // Called after path defaults are computed, before Runtime is constructed
    void OnConfigurePaths(rex::PathConfig& paths) override {
        auto exe_dir = rex::filesystem::GetExecutableFolder();
        OutputDebugStringA("OnConfigurePaths START\n");
        REXLOG_INFO("OnConfigurePaths - exe_dir: {}", exe_dir.string());
        
        // Game directory: arg or default to the project assets dir.
        // The exe lives in out/build/win-amd64-release (or build/Release),
        // so walk up parent directories until one contains an "assets" folder.
        std::filesystem::path game_dir;
        if (auto arg = GetArgument("game_directory")) {
            game_dir = *arg;
            REXLOG_INFO("OnConfigurePaths - game_dir from arg: {}", game_dir.string());
        } else {
            std::filesystem::path probe = exe_dir;
            bool found = false;
            for (int depth = 0; depth < 6 && !found; ++depth) {
                auto candidate = probe / "assets";
                if (std::filesystem::is_directory(candidate)) {
                    game_dir = candidate;
                    found = true;
                    REXLOG_INFO("OnConfigurePaths - game_dir default (assets found at {}): {}",
                                probe.string(), game_dir.string());
                } else {
                    probe = probe.parent_path();
                }
            }
            if (!found) {
                game_dir = exe_dir;
                REXLOG_INFO("OnConfigurePaths - assets not found, using exe dir: {}", game_dir.string());
            }
        }
        
        REXLOG_INFO("OnConfigurePaths - game_dir final: {}", game_dir.string());
        paths.game_data_root = game_dir;
        paths.user_data_root = exe_dir / "user_data" / GetName();
        paths.cache_root = paths.user_data_root / "cache";
        paths.metadata_root = exe_dir / "metadata";
        REXLOG_INFO("OnConfigurePaths - game_data_root set to: {}", paths.game_data_root.string());
        OutputDebugStringA("OnConfigurePaths END\n");
    }

    // Called when the main guest thread exits
    void OnGuestThreadExit(rex::system::XThread* thread) override {
        (void)thread;
        REXLOG_CRITICAL("=== GUEST THREAD EXITED ===");
        REXLOG_CRITICAL("This should not happen during normal gameplay - likely XamLoaderTerminateTitle called for module transition");
        
        // DON'T quit - the game is transitioning modules (intro -> menu)
        // ReXApp should handle relaunching, but for now prevent hard exit
        // shutting_down_.store(true, std::memory_order_release);
        // app_context().QuitFromUIThread();
        
        // Try to relaunch module
        REXLOG_INFO("Attempting to relaunch module after transition...");
        if (auto* rt = runtime()) {
            REXLOG_INFO("Runtime available, checking kernel state...");
            if (rt->kernel_state()) {
                REXLOG_INFO("Kernel state available, checking if title is terminating...");
                REXLOG_INFO("terminating_title flag: {}", rt->kernel_state()->is_terminating_title() ? "true" : "false");
            } else {
                REXLOG_ERROR("No kernel state available!");
            }
            
            REXLOG_INFO("Calling LaunchModule()....");
            if (auto main_thread = rt->LaunchModule()) {
                REXLOG_INFO("Module relaunched successfully");
                transition_thread_ = std::thread([this, main_thread = std::move(main_thread)]() mutable {
                    REXLOG_INFO("Waiting for relaunched module thread...");
                    main_thread->Wait(0, 0, 0, nullptr);
                    REXLOG_INFO("Execution complete after relaunch");
                    if (!shutting_down_.load(std::memory_order_acquire)) {
                        app_context().CallInUIThread([this]() {
                            app_context().QuitFromUIThread();
                        });
                    }
                });
            } else {
                REXLOG_ERROR("LaunchModule() returned null - failed to relaunch module");
                shutting_down_.store(true, std::memory_order_release);
                app_context().QuitFromUIThread();
            }
        } else {
            REXLOG_ERROR("No runtime available, quitting");
            shutting_down_.store(true, std::memory_order_release);
            app_context().QuitFromUIThread();
        }
    }

    // Called before cleanup begins
    void OnShutdown() override {
        REXLOG_INFO("OnShutdown called");
    }

protected:
    // Gate the real module launch behind the launcher "Play" button.
    // OnInitialize calls this automatically; while the launcher is shown we
    // do nothing and let the dialog's on_play callback trigger the launch.
    void LaunchModule() override {
        if (REXCVAR_GET(dbz1_skip_launcher)) {
            REXLOG_INFO("dbz1: skip_launcher set, booting directly");
            ReXApp::LaunchModule();
            return;
        }
        REXLOG_INFO("dbz1: launcher shown, waiting for Play");
    }

    // Handle window close request
    bool OnWindowCloseRequested() override {
        REXLOG_INFO("Window close requested");
        shutting_down_.store(true, std::memory_order_release);
        if (auto* rt = runtime(); rt && rt->kernel_state()) {
            rt->kernel_state()->TerminateTitle();
        }
        return true; // Allow close
    }

private:
    std::unique_ptr<DebugOverlayDialog> debug_overlay_;
    dbz1::launcher::LauncherDialog* launcher_dialog_ = nullptr;
    std::unique_ptr<dbz1::ingame::InGameMenu> ingame_menu_;
    std::atomic<bool> launched_{false};
    std::atomic<bool> shutting_down_{false};
    std::thread transition_thread_;
    rex::ui::Window* window_ = nullptr;
    rex::ui::ImGuiDrawer* imgui_drawer_ = nullptr;
    static std::atomic<bool> crash_logged_;

    // Keeps old logs and crash dumps from accumulating forever: retains the
    // most recent N files matching a glob pattern in a directory, deleting the
    // rest (oldest first).
    static void PruneOldFiles(const std::filesystem::path& dir,
                              const std::string& pattern, size_t keep) {
        std::error_code ec;
        if (!std::filesystem::is_directory(dir, ec)) {
            return;
        }
        std::vector<std::filesystem::path> matches;
        for (const auto& entry : std::filesystem::directory_iterator(dir, ec)) {
            if (!entry.is_regular_file(ec)) {
                continue;
            }
            if (entry.path().filename().string().find(pattern) == 0) {
                matches.push_back(entry.path());
            }
        }
        if (matches.size() <= keep) {
            return;
        }
        std::sort(matches.begin(), matches.end(),
                  [](const std::filesystem::path& a, const std::filesystem::path& b) {
                      std::error_code ec1, ec2;
                      const auto ta = std::filesystem::last_write_time(a, ec1);
                      const auto tb = std::filesystem::last_write_time(b, ec2);
                      if (ec1 || ec2) return false;
                      return ta > tb;
                  });
        for (size_t i = keep; i < matches.size(); ++i) {
            std::error_code rm_ec;
            std::filesystem::remove(matches[i], rm_ec);
            if (!rm_ec) {
                REXLOG_INFO("dbz1: pruned old file {}", matches[i].string());
            }
        }
    }

    static void CleanupOldArtifacts() {
        const std::filesystem::path cwd = std::filesystem::current_path();
        // Keep the 10 most recent session logs and the 3 most recent dumps.
        PruneOldFiles(cwd / "logs", "dbz1_", 10);
        PruneOldFiles(cwd, "crash_", 3);
    }

    static void SetupCrashHandler() {
#if REX_PLATFORM_WIN32
        SetUnhandledExceptionFilter([](EXCEPTION_POINTERS* ep) -> LONG {
            if (crash_logged_.exchange(true)) return EXCEPTION_CONTINUE_SEARCH;
            
            auto now = std::chrono::system_clock::now();
            auto time_t = std::chrono::system_clock::to_time_t(now);
            char timestamp[64];
            strftime(timestamp, sizeof(timestamp), "%Y%m%d_%H%M%S", std::localtime(&time_t));
            
            char dump_path[MAX_PATH];
            snprintf(dump_path, sizeof(dump_path), "crash_%s.dmp", timestamp);
            
            HANDLE hFile = CreateFileA(dump_path, GENERIC_WRITE, 0, nullptr, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
            if (hFile != INVALID_HANDLE_VALUE) {
                MINIDUMP_EXCEPTION_INFORMATION mei;
                mei.ThreadId = GetCurrentThreadId();
                mei.ExceptionPointers = ep;
                mei.ClientPointers = FALSE;
                MiniDumpWriteDump(GetCurrentProcess(), GetCurrentProcessId(), hFile, MiniDumpNormal, &mei, nullptr, nullptr);
                CloseHandle(hFile);
                OutputDebugStringA("Crash dump written to ");
                OutputDebugStringA(dump_path);
                OutputDebugStringA("\n");
            }
            REXLOG_CRITICAL("UNHANDLED EXCEPTION: Code=0x{:08X} Addr={:p}", 
                ep->ExceptionRecord->ExceptionCode, ep->ExceptionRecord->ExceptionAddress);
            return EXCEPTION_EXECUTE_HANDLER;
        });
        
        // Also catch abort()
        std::set_terminate([]() {
            REXLOG_CRITICAL("std::terminate called!");
            std::abort();
        });
#endif
    }
};

std::atomic<bool> Dbz1App::crash_logged_{false};

XE_DEFINE_WINDOWED_APP(dbz1, Dbz1App::Create)

// External kernel imports (stubs for Windows kernel functions)
REX_EXTERN(__imp__IoInvalidDeviceRequest);
REX_EXTERN(__imp__ObReferenceObject);
REX_EXTERN(__imp__IoDeleteDevice);
REX_EXTERN(__imp__IoCompleteRequest);
REX_EXTERN(__imp__NtWriteFileGather);
REX_EXTERN(__imp__RtlUpcaseUnicodeChar);
REX_EXTERN(__imp__ObIsTitleObject);
REX_EXTERN(__imp__IoCheckShareAccess);
REX_EXTERN(__imp__IoSetShareAccess);
REX_EXTERN(__imp__IoRemoveShareAccess);
REX_EXTERN(__imp__XeCryptBnQwBeSigVerify);
REX_EXTERN(__imp__XeKeysGetKey);
REX_EXTERN(__imp__XeCryptRotSumSha);